CREATE DATABASE IF NOT EXISTS PAGE_VISITS;

USE PAGE_VISITS

CREATE TABLE PAGE_VISITS (
  id    INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SHAPE VARCHAR(32),
  TS    TIMESTAMP
) AUTO_INCREMENT=1;
